version: "3.8"
services:
  app :
    build: ./app/
  db:
    build: ./database/
  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    depends_on:
    - db
    ports:
    - "8080:8080"
